# Generated by Django 3.1.3 on 2020-12-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
